esphome:
  name: lane-upper-flood
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: lane-upper-flood.pimblett.me.uk

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

logger:
  level: DEBUG

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff onboard switch"
    on_press:
      - light.toggle: light_relay

output:
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: binary
    name: "Lane Upper Flood"
    output: relay
    id: light_relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
