esphome:
  name: nmcu
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: nmcu.pimblett.me.uk

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    name: Wire
    pin:
      number: D0
      mode: INPUT_PULLUP

switch:
  - platform: gpio
    name: Beep
    pin:
      number: D1

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 10s
    model: DHT11
